name: online-entrance-preparation-backend
version: "3.9"

services:
  db:
    image: postgres:16
    container_name: online_entrance_preparation_db
    restart: always
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  web:
    build: .
    container_name: online_entrance_preparation_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.dev

volumes:
  postgres_data:
