# Generated by Django 6.0.1 on 2026-03-15 16:31

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abbr', models.CharField(max_length=10)),
                ('total_questions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('question_to_select', models.IntegerField(default=0)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmes.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='only_one_correct_option')],
                'unique_together': {('question', 'option')},
            },
        ),
    ]
