# Generated by Django 6.0.1 on 2026-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
