# Generated by Django 6.0.1 on 2026-03-19 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0002_alter_option_option_alter_programme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programmes.programme'),
        ),
    ]
