# Generated by Django 6.0.1 on 2026-03-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0004_alter_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Programmes.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Programmes.programme'),
        ),
    ]
